spring:
  mongodb:
    uri: mongodb://localhost:27017/cracdemo
  datasource:
    url: jdbc:postgresql://localhost:5432/cracdemo
    username: cracdemo
    password: cracdemo
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 0
      maximum-pool-size: 10
      allow-pool-suspension: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

env: ${ENV:Hello from application.yml}



